### ISSUE TITLE
qtwebkit claimed for OpenBoard ebuild [solved]

### ISSUE THREAD

**Issue by novazur972** [cloc3/OpenBoard#2]
Wouldn't it be necessary to adapt the OpenBoard ebuild to the current portage state?
Indeed, it is unfortunately impossible to install it as is:
emerge: there are no ebuilds to satisfy "dev-qt/qtwebkit".
(dependency required by "x11-apps/OpenBoard-1.6.4" [ebuild])
(dependency required by "OpenBoard" [argument])

**Comment by cloc3** [comment]
Thank's for your request.
Sorry if I'm a bit slow in my responses.

Now dev-qt/qtwebkit is no more needed for Openboard-1.7.x
A new version is available on this repository.

At the moment, only qt5 support is available, because I need time to update my gentoo box.
Thanks also for your hint about "startupHints"
